### ISSUE TITLE
Allow set an empty path on constructor

### ISSUE THREAD

**Issue by eusonlito** [slutske22/leaflet-spline#2]
The plugin constructor requires that path on start, but on my usage (for example) I'm starting with an empty Polyline and filled with points on advanced point after. Then, the plugin fails:

```js
setPolyline() {
    this.line = L.spline([], {
        weight: 5,
        opacity: 1,
        smoothFactor: 1
    }).addTo(this.layer);

    return this;
}

setLinePoints(points) {
    this.line.setLatLngs(points);

    return this;
}
```

```
index.js:95 Uncaught TypeError: Cannot read properties of undefined (reading 'lat')
    at Spline._transformPoints (index.js:95:26)
    at new Spline (index.js:84:15)
    at Object.spline (index.js:338:12)
```

**Comment by slutske22** [comment]
It doesn't make much sense to draw a spline for an array of less than 3 points, but I see your use case.  I don't know that I have time anytime soon to update this, you may have to adjust the source code yourself, or make accomodations in your code that a spline is not drawn until at least 3 points are available

**Comment by eusonlito** [comment]
It's live track 😅 then the points are added to polyline every 10 seconds.

**Comment by slutske22** [comment]
That's fine.  My guess is that on page load, you start with no data, then as points come in, you being adding.  In those first 20 seconds, you either have 0, 1, or 2 points on screen.  You cannot draw a spline until you have 3 points.  You can add some custom code to test the length of your point array, and draw the correct geometry accordingly.  Some pseudocode:

```
if points.length === 1
  draw a dot
if points.length === 2
 remove the dot, draw a polyline
if points.length === 3
  remove the polyline, draw a spline
if points.length > 3
  drawn a spline, or add points to the existing spline
```

Ultimately this plugin is concerned with drawing splines, not with how to manage *when it is valid* to draw a spline
