### ISSUE TITLE
Can be used with other plugins?

### ISSUE THREAD

**Issue by eusonlito** [slutske22/leaflet-spline#3]
Maybe is a Leaflet related issue, but... can be used this plugin toghether other plugins, like https://github.com/Oliv/leaflet-polycolor

Something as:

```js
const line = L.polycolor([], options)
    .spline()
    .addTo(layer);
```

Thanks!

**Comment by slutske22** [comment]
Probably not right out of the box. You'd need to adjust the source code to do that.  But considering the number of plugins that are available for leaflet, that's something you would need to do on a case-by-case basis, and not an issue with this plugin.

**Comment by eusonlito** [comment]
Ok, thanks!
