### ISSUE TITLE
Integrating with older site

### ISSUE THREAD

**Issue by rsparkyc** [slutske22/leaflet-spline#5]
I'm trying to integrate this into an older site that doesn't use node, is it possible to host the javascript on a CDN somewhere where I can just import it using a `<script>` tag?

**Comment by slutske22** [comment]
You can try [unpkg](https://www.unpkg.com/).  Script would be here: https://www.unpkg.com/leaflet-spline@0.2.0/build/index.js

**Comment by rsparkyc** [comment]
I tried using that, but when I try to do L.spline, it says that function is not defined. I see this requires leaflet-curve, I tried importing that as well via a CDN, but still get nothing.

**Comment by slutske22** [comment]
Unfortunately I never thought of that use case, and I don't have much bandwidth ATM.

Have you tried using just leaflet-curve via CDN to see if that works?  If that doesn't work, then this plugin (which is built on top of that) definitely wont.

Fee free to just copy and paste the source code, modify it, and use it as a script in your site.

**Comment by rsparkyc** [comment]
yeah, it loads curve. I'll need to mess with it more to see why it doesn't see the spline function.

**Comment by XavierBouhours** [comment]
Chat GPT make the ts to js convertion for us. Load leaflet.js and leaflet-curve.1.0.js in your HTML. It's good for me. Here is the javascript no-minimized version :
`
/** leaflet-spline.2.0.js
 * Get line length and bearing
 */
const line = (coord1, coord2) => {
  const lengthX = coord2.x - coord1.x;
  const lengthY = coord2.y - coord1.y;

  return {
    length: Math.sqrt(Math.pow(lengthX, 2) + Math.pow(lengthY, 2)),
    angle: Math.atan2(lengthY, lengthX),
  };
};

/**
 * Gets 2 cubic bezier control points given a current, previous, and next point
 */
const controlPoint = (smoothing, map, current, previous, next, reverse) => {
  const p = previous || current;
  const n = next || current;

  const currPoint = map.latLngToLayerPoint(L.latLng(current));
  const prevPoint = map.latLngToLayerPoint(L.latLng(p));
  const nextPoint = map.latLngToLayerPoint(L.latLng(n));

  let { length, angle } = line(prevPoint, nextPoint);

  angle = angle + (reverse ? Math.PI : 0);
  length = length * smoothing;

  const x = currPoint.x + Math.cos(angle) * length;
  const y = currPoint.y + Math.sin(angle) * length;

  const { lat, lng } = map.layerPointToLatLng([x, y]);
  return [lat, lng];
};

class Spline extends L.Polyline {
  constructor(path, options = {}) {
    super(path, options);
    this._curve = new L.Curve([], { ...options });
    this._smoothing = options.smoothing || 0.15;
    this._points = [];
    this._transformPoints(path);
  }

  _transformPoints(path) {
    if (Array.isArray(path[0]) && path[0].length === 2) {
      this._points = path;
    } else if (path[0].lat) {
      this._points = path.map(latlng => [latlng.lat, latlng.lng]);
    }
  }

  drawBezier() {
    if (this._map) {
      let points = [...this._points];
      const first = [...points[0]];

      const pl = points.length;
      const isClosedShape = points[0][0] === points[pl - 1][0] && points[0][1] === points[pl - 1][1];

      const controlPoints = [];
      for (let i = 0; i < pl - 1; i++) {
        controlPoints.push(controlPoint(this._smoothing, this._map, points[i], points[i + 1], points[i - 1]));
        controlPoints.push(controlPoint(this._smoothing, this._map, points[i], points[i - 1], points[i + 1]));
      }

      if (!isClosedShape) {
        controlPoints.shift();
        controlPoints.push(controlPoint(this._smoothing, this._map, points[pl - 1], undefined, points[pl - 2]));
      } else {
        const firstCp = controlPoints.shift();
        controlPoints.push(firstCp);

        controlPoints[0] = controlPoint(this._smoothing, this._map, points[pl - 1], points[pl - 2], points[1]);
        controlPoints[controlPoints.length - 1] = controlPoint(this._smoothing, this._map, points[pl - 1], points[1], points[pl - 2]);
      }

      const commands = ["M", first];

      points = [...this._points];

      const lineTo = points.shift();
      commands.push(...["L", lineTo]);

      while (points.length > 0) {
        const cp1 = controlPoints.shift();
        const cp2 = controlPoints.shift();
        const destination = points.shift();
        commands.push(...["C", cp1, cp2, destination]);
      }

      if (isClosedShape) {
        commands.push("Z");
      }

      if (!this._curve) {
        this._curve = L.curve(commands, { ...this.options });
      } else {
        this._curve.setPath(commands);
      }
    }

    return this._curve;
  }

  update() {
    this.drawBezier();
  }

  onAdd(map) {
    this.drawBezier();
    this._curve.addTo(map);

    map.on("zoomend", () => {
      this.update();
    });

    return this;
  }

  onRemove(map) {
    map.off("zoomend", () => {
      this.update();
    });
    this._curve.remove();
    return this;
  }

  on(type, fn, context) {
    this._curve.on(type, fn, context);
    return this;
  }
  off(type, fn, context) {
    this._curve.off(type, fn, context);
    return this;
  }
  once(type, fn, context) {
    this._curve.once(type, fn, context);
    return this;
  }
  fire(type, data, propagate) {
    this._curve.once(type, data, propagate);
    return this;
  }
  listens(type) {
    return this._curve.listens(type);
  }
  addEventParent(obj) {
    this._curve.addEventParent(obj);
    return this;
  }
  removeEventParent(obj) {
    this._curve.removeEventParent(obj);
    return this;
  }
  addEventListener(type, fn, context) {
    this._curve.addEventListener(type, fn, context);
    return this;
  }
  removeEventListener(type, fn, context) {
    this._curve.removeEventListener(type, fn, context);
    return this;
  }
  clearAllEventListeners() {
    this._curve.clearAllEventListeners();
    return this;
  }
  fireEvent(type, data, propagate) {
    this._curve.fireEvent(type, data, propagate);
    return this;
  }
  hasEventListeners(type) {
    return this._curve.hasEventListeners(type);
  }
  remove() {
    this._curve.remove();
    return this;
  }
  removeFrom(map) {
    this._curve.removeFrom(map);
    return this;
  }
  getPane(name) {
    return this._curve.getPane(name);
  }
  bindPopup(content, options) {
    this._curve.bindPopup(content, options);
    return this;
  }
  unbindPopup() {
    this._curve.unbindPopup();
    return this;
  }
  openPopup(latlng) {
    this._curve.openPopup(latlng);
    return this;
  }
  closePopup() {
    this._curve.closePopup();
    return this;
  }
  togglePopup() {
    this._curve.togglePopup();
    return this;
  }
  isPopupOpen() {
    return this._curve.isPopupOpen();
  }
  setPopupContent(content) {
    this._curve.setPopupContent(content);
    return this;
  }
  getPopup() {
    return this._curve.getPopup();
  }
  bindTooltip(content, options) {
    this._curve.bindTooltip(content, options);
    return this;
  }
  unbindTooltip() {
    this._curve.unbindTooltip();
    return this;
  }
  openTooltip(latlng) {
    this._curve.openTooltip(latlng);
    return this;
  }
  closeTooltip() {
    this._curve.closeTooltip();
    return this;
  }
  toggleTooltip() {
    this._curve.toggleTooltip();
    return this;
  }
  isTooltipOpen() {
    return this._curve.isTooltipOpen();
  }
  setTooltipContent(content) {
    this._curve.setTooltipContent(content);
    return this;
  }
  getTooltip() {
    return this._curve.getTooltip();
  }
  redraw() {
    this._curve.redraw();
    return this;
  }
  setStyle(style) {
    L.Util.setOptions(this, style);
    this._curve.setStyle(style);
    return this;
  }
  bringToFront() {
    this._curve.bringToFront();
    return this;
  }
  bringToBack() {
    this._curve.bringToBack();
    return this;
  }
  getElement() {
    return this._curve.getElement();
  }
  setLatLngs(latlngs) {
    this._transformPoints(latlngs);
    this.drawBezier();
    return this;
  }
  trace(samplingDistance) {
    return this._curve.trace(samplingDistance);
  }
}

function spline(path, options = {}) {
  return new Spline(path, options);
}

L.Spline = Spline;
L.spline = spline;
`
