### ISSUE TITLE
draw error with leaflet draw

### ISSUE THREAD

**Issue by mlhrnl** [slutske22/leaflet-spline#6]
Hello, this is a great plugin but i have a problem.

When I add this plugin, I can't draw with leaflet draw. For example, for polygon 'TypeError: Cannot read properties of undefined (reading 'Polygon')' error. Thank you in advance for your attention

I would appreciate your help

**Comment by slutske22** [comment]
I have not tried to combine this with leaflet-draw.  My guess is leaflet-draw also modified some of the leaflet primitives, like L.Polyline, but I am not very familiar with it.

Also, without a minimum reproducible example of your scenario (code example, codesandbox etc), I have no idea what your code is or what its doing.  I'll leave this open as a courtesy to give you a chance to put up a min rep ex, but this issue, the way you've written it, is impossible to address.

**Comment by slutske22** [comment]
30 days no response or reproducible example, closing
